

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

jdoodle.clientId=${JDOODLE_CLIENT_ID}
jdoodle.clientSecret=${JDOODLE_CLIENT_SECRET}

spring.app.jwtSecret=${SPRING_APP_JWT_SECRET}
spring.app.jwtExpirationMs=${SPRING_APP_JWT_EXPIRATION_MS}
spring.app.jwtCookieName=${SPRING_APP_JWT_COOKIE_NAME}
