spring.application.name=DriveDesk


spring.datasource.url=jdbc:postgresql://localhost:5432/DriveDesk
spring.datasource.username=postgres
spring.datasource.password=pravin@21
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.app.jwtSecret=VGhpcy1pcy1teS1zZWNyZXQta2V5LWZvci1hc3Nlc3NtZW50LXBvcnRhbA==
spring.app.jwtExpirationMs=86400000   
spring.app.jwtCookieName=DriveDeskJwt

logging.level.org.springframework.security=DEBUG
logging.level.com.project.exam_portal=DEBUG

